config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  
  root "questions#index"
  
  resources :questions do
    resource :vote, only: [:create, :destroy], module: :questions
    resources :comments, only: :create, module: :questions
    
    resources :answers, only: :create do
      resource :vote, only: [:create, :destroy], module: :answers
      resources :comments, only: :create, module: :answers
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_many :votes, as: :votable
  has_many :comments, as: :commentable

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :body, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :votes, as: :votable
  has_many :comments, as: :commentable

  validates  :title, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
  belongs_to :user
end

app/controllers/answers/comments_controller.rb
class Answers::CommentsController < CommentsController
  before_action :set_commentable

  private
  def set_commentable
    @commentable = Answer.find(params[:answer_id])
  end
end

app/controllers/answers/votes_controller.rb
class Answers::VotesController < VotesController
  before_action :set_votable

  private
  def set_votable
    @votable = Answer.find(params[:answer_id])
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    question = Question.find(params[:question_id])
    question.answers.create(answers_params)

    redirect_to question
  end

  private
  def answers_params
    params.require(:answer).permit(:body).merge(user: current_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @commentable.comments.create(comments_params)

    redirect_to question_path(params[:question_id])
  end

  private
  def comments_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable

  private
  def set_commentable
    @commentable = Question.find(params[:question_id])
  end
end

app/controllers/questions/votes_controller.rb
class Questions::VotesController < VotesController
  before_action :set_votable

  private
  def set_votable
    @votable = Question.find(params[:question_id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :find_question, only: [:show]

  def index
    @questions = Question.order(created_at: :desc)

    @questions = @questions.where("title || description ILIKE ?", "%#{params[:query]}%") if params[:query].present?
  end

  def new
    @question = Question.new
  end  

  def show

  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to questions_path, notice: "La pregunta fue creada con éxito"
    else
      render :new  
    end  
  end

  private
  def question_params
    params.require(:question).permit(:title, :description).merge(user: current_user)
  end

  def find_question
    @question = Question.find(params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def create
    @votable.votes.create(user: current_user)

    redirect_to question_path(params[:question_id])
  end

  def destroy
    @votable.votes.where(user: current_user).take.try(:destroy)

    redirect_to question_path(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" class="text-danger">
      <span>#{sentence}</span>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/questions/index.html.erb
<h1 class="mt-4">Preguntas</h1>

<div class="text-right mb-2">
  <%= link_to "Hacer una pregunta", new_question_path, class: "btn btn-primary btn-lg" %>
</div>

<% @questions.each do |question| %>
  <hr>
  <div class="row">
    <div class="col-md-3">
      <div class="row">
        <div class="col-md-6 text-center">
          <h4><%= question.votes.count %></h4>
          <p class="text-muted">Votos</p>
        </div>
        <div class="col-md-6 text-center">
          <h4><%= question.answers.count %></h4>
          <p class="text-muted">Respuestas</p>
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <h3 class="text-primary"><%= link_to question.title, question_path(question.id) %></h3>
      <p class="text-muted">
        Preguntó <%= User.find(question.user_id).email %> hace <%= time_ago_in_words(question.created_at) %>
      </p>
    </div>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="container">
  <div class="row">

    <% if @question.errors.any? %>
    <div class="col-md-6 offset-md-3 mt-5">
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li class="text-danger"><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="col-md-6 offset-md-3 <%= @question.errors.any? ? "" : "mt-5" %>">
      <h1 class="mb-4">Crear pregunta</h1>
      <%= form_for @question do |f| %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <div class="form-group">
          <%= f.text_field :title, class: "form-control", placeholder: "Título" %>
        </div>
        <div class="form-group">
          <%= f.text_area :description, size: "25x8", class: "form-control", placeholder: "Descripción" %>
        </div>
        <div>
          <%= f.submit "Publicar Producto", class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @question.title %></h1>
    </div>

    <div class="col-sm-12 mt-3">
      <div class="row">

        <div class="col-md-1 text-center">
          <% if @question.votes.exists?(user_id: current_user ) %>
            <%= link_to question_vote_path(@question), method: :delete, class: "product-upvote upvote-active" do %>
              <%= render "votes/vote", type: @question %>
            <% end %>
          <% else %>
            <%= link_to question_vote_path(@question), method: :post, class: "product-upvote" do %>
              <%= render "votes/vote", type: @question %>
            <% end %>
          <% end %>
        </div>
        <div class="col-md-11">
          <%= markdown(@question.description) %>

          <% if @question.comments.count > 0 %>
            <h3 class="mt-4">Comentarios</h3>
          <% end %>

          <% @question.comments.each do |comment| %>
            <hr>
            <p class="text-muted">
              <%= comment.body %>
            </p>
          <% end %>

          <% if user_signed_in? %>
            <%= form_for [@question, @question.comments.build] do |f| %>
              <div class="form-group mt-5">
                <%= f.text_area :body, class: "form-control", placeholder: "Agregar comentario" %>
              </div>

              <div class="text-right">
                <%= f.submit "Comentar", class: "btn btn-primary" %>
              </div>
            <% end %>
          <% end %>
        </div>

      </div>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-sm-12">
      <h3><%= @question.answers.count %> Respuesta(s)</h3>
      <hr>
    </div>
    <% if @question.answers.count == 0 %>
      <div class="col-sm-12">
        <p class="text-muted">
          Si conoces alguien que pueda responder esta pregunta por favor timbrale y dile que lo necesitamos con urgencia.
        </p>
      </div>
    <% end %>
  </div>

  <div class="row">
    <% @question.answers.each do |answer| %>
        <div class="col-md-1 text-center">
          <% if answer.votes.exists?(user_id: current_user ) %>
            <%= link_to question_answer_vote_path(@question, answer), method: :delete, class: "product-upvote upvote-active" do %>
              <%= render "votes/vote", type: answer %>
            <% end %>
          <% else %>
            <%= link_to question_answer_vote_path(@question, answer), method: :post, class: "product-upvote" do %>
              <%= render "votes/vote", type: answer %>
            <% end %>
          <% end %>
        </div>
        <div class="col-md-11">
          <%= markdown(answer.body) %>

          <% if answer.comments.count > 0 %>
            <h3 class="mt-4">Comentarios</h3>
          <% end %>

          <% answer.comments.each do |comment| %>
            <hr>
            <p class="text-muted">
              <%= comment.body %>
            </p>
          <% end %>

          <% if user_signed_in? %>
            <%= form_for Comment.new, url: question_answer_comments_path(@question, answer) do |f| %>
              <div class="form-group mt-5">
                <%= f.text_area :body, class: "form-control", placeholder: "Agregar comentario" %>
              </div>

              <div class="text-right">
                <%= f.submit "Comentar", class: "btn btn-primary" %>
              </div>
            <% end %>
          <% end %>

        </div>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <h3 class="mt-4">Tu respuesta</h3>
    <hr>
    <%= form_for [@question, @question.answers.build] do |f| %>
      <div class="form-group">
        <%= f.text_area :body, size: "25x8", class: "form-control", placeholder: "Agregar respuesta" %>
      </div>

      <div class="text-right">
        <%= f.submit "Enviar respuesta", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>

</div>

app/views/votes/_vote.html.erb
<span class="upvote-arrow"></span>
<span class="upvote-count"><%= type.votes.count %></span>